### ISSUE TITLE
Unknown extensions with non-DER data

### ISSUE THREAD

**Issue by madwizard-thomas** [sop/x509#3]
I'm developing a webauthn implementation and am using your library to parse attestation certificates of authentication keys. Your library fails parsing one widely used device ([Yubico security key](https://www.yubico.com/product/security-key-by-yubico/)). Looking into the issue I found that the certificate is using three vendor specific extensions, but one of them has a plain text string encoded as the extension value (extnValue) octetstring. Normally the octetstring contains DER encoded data and your library creates an UnknownExtension with a DERData value. This fails if the extension does not contain valid DER.

It seems like the specs require the extension value to be valid DER although I'm not sure of this. Either way I'm a bit stuck now since I still would like to keep using your library for the parsing but also will have to support this certificate since it is in wide use already. Would there be any way to work around this issue?

The extensions decoded are:
```
  322:d=3  hl=2 l= 106 cons:    SEQUENCE
  324:d=4  hl=2 l=  34 cons:     SEQUENCE
  326:d=5  hl=2 l=   9 prim:      OBJECT            :1.3.6.1.4.1.41482.2
  337:d=5  hl=2 l=  21 prim:      OCTET STRING      :1.3.6.1.4.1.41482.1.1    <-- not wrapped
  360:d=4  hl=2 l=  19 cons:     SEQUENCE
  362:d=5  hl=2 l=  11 prim:      OBJECT            :1.3.6.1.4.1.45724.2.1.1
  375:d=5  hl=2 l=   4 prim:      OCTET STRING      [HEX DUMP]:03020520  <-- wrapped bitstring
  381:d=4  hl=2 l=  33 cons:     SEQUENCE
  383:d=5  hl=2 l=  11 prim:      OBJECT            :1.3.6.1.4.1.45724.1.1.4
  396:d=5  hl=2 l=  18 prim:      OCTET STRING      [HEX DUMP]:0410F8A011F38C0A4D15800617111F9EDC7D <-- wrapped octetstring
  416:d=4  hl=2 l=  12 cons:     SEQUENCE
  418:d=5  hl=2 l=   3 prim:      OBJECT            :X509v3 Basic Constraints
  423:d=5  hl=2 l=   1 prim:      BOOLEAN           :255
  426:d=5  hl=2 l=   2 prim:      OCTET STRING      [HEX DUMP]:3000
```
The certificate is:
```
-----BEGIN CERTIFICATE-----
MIICvjCCAaagAwIBAgIEdIb9wjANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQD
EyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4
MDEwMDAwMDBaGA8yMDUwMDkwNDAwMDAwMFowbzELMAkGA1UEBhMCU0UxEjAQ
BgNVBAoMCVl1YmljbyBBQjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRl
c3RhdGlvbjEoMCYGA1UEAwwfWXViaWNvIFUyRiBFRSBTZXJpYWwgMTk1NTAw
Mzg0MjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJVd8633JH0xde/9nMTz
Gk6HjrrhgQlWYVD7OIsuX2Unv1dAmqWBpQ0KxS8YRFwKE1SKE1PIpOWacE5S
O8BN6+2jbDBqMCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS4x
MBMGCysGAQQBguUcAgEBBAQDAgUgMCEGCysGAQQBguUcAQEEBBIEEPigEfOM
Ck0VgAYXER+e3H0wDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEA
MVxIgOaaUn44Zom9af0KqG9J655OhUVBVW+q0As6AIod3AH5bHb2aDYakeIy
yBCnnGMHTJtuekbrHbXYXERIn4aKdkPSKlyGLsA/A+WEi+OAfXrNVfjhrh7i
E6xzq0sg4/vVJoywe4eAJx0fS+Dl3axzTTpYl71Nc7p/NX6iCMmdik0pAuYJ
egBcTckE3AoYEg4K99AM/JaaKIblsbFh8+3LxnemeNf7UwOczaGGvjS6UzGV
I0Odf9lKcPIwYhuTxM5CaNMXTZQ7xq4/yTfC3kPWtE4hFT34UJJflZBiLrxG
4OsYxkHw/n5vKgmpspB3GfYuYTWhkDKiE8CYtyg87g==
-----END CERTIFICATE-----
```

**Comment by sop** [comment]
Extension value should indeed be valid DER, which is not the case with Yubico's extension. This is specified (albeit loosely as a comment) in [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.1), see `Extension` -> `extnValue`.

I've now added support for extensions with non-conforming values. There's also a method in `UnknownExtension` class to retrieve the raw extension payload.

I'll push a new tag soon.

**Comment by madwizard-thomas** [comment]
Great, thanks a lot!
