### ISSUE TITLE
sop/x509 crashes when handling Certificates with Name Constraints

### ISSUE THREAD

**Issue by 5pr1nz** [sop/x509#5]
## Preamble
Certificates (of intermediate CAs) can be extended with name constraints. 
These can restrict the ca to only be able to validate the authenticity of certain Name such as rfc822Name, DNS, IP, etc. (see [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.10)).

For example, the constraint "example.com" is satisfied by any mail address at the host "example.com".
```
X509v3 Name Constraints: critical
    Permitted:
        email:example.com
```

## Bug report
The x509 library fails to load certificates containing name constraints of type ```RFC822Name```.

```
PHP Fatal error:  Uncaught RuntimeException: Integer overflow. in /vendor/sop/asn1/lib/ASN1/Util/BigInt.php:129
Stack trace:
#0 /vendor/sop/asn1/lib/ASN1/Type/Primitive/Integer.php(62): Sop\ASN1\Util\BigInt->intVal()
#1 /vendor/sop/x509/lib/X509/Certificate/Extension/NameConstraints/GeneralSubtree.php(74): Sop\ASN1\Type\Primitive\Integer->intNumber()
#2 /vendor/sop/x509/lib/X509/Certificate/Extension/NameConstraints/GeneralSubtrees.php(46): Sop\X509\Certificate\Extension\NameConstraints\GeneralSubtree::fromASN1()
#3 [internal function]: Sop\X509\Certificate\Extension\NameConstraints\GeneralSubtrees::Sop\X509\Certificate\Extension\NameConstraints\{closure}()
#4 /vendor/sop/x509/lib/X509/Certificate/Extension/NameConstraints/GeneralSubtrees.php(47): array_map()
#5 /vendor/sop/x509/lib/X509/Certifica in /vendor/sop/asn1/lib/ASN1/Util/BigInt.php on line 129
```

Other name constraints seem to work, as tested with ```DNSName``` and ```IPAddress```.

## Setup for reproduction

[ac-example.php](https://github.com/sop/x509/blob/master/examples/ac-example.php) can be used to reproduce the bug.

Amend the following lines, starting at the block "create AC issuer certificate" after line 77:
* Add a ```NameConstraintExtension``` after line 90
  ```php
  new NameConstraintsExtension(true,
    new GeneralSubtrees(
        new GeneralSubtree(
            new RFC822Name('example.com'))))
  ```
* Re-read the signed certificate after line 94

A working example looks as follows:
```php
// create AC issuer certificate
$tbs_cert = new TBSCertificate(
    Name::fromString('cn=Issuer'),
    $issuer_private_key->publicKeyInfo(),
    new Name(),
    Validity::fromStrings('now', 'now + 6 months'));
$tbs_cert = $tbs_cert->withIssuerCertificate($ca_cert)
    ->withRandomSerialNumber()
    ->withAdditionalExtensions(
        // issuer must not be a CA
        new BasicConstraintsExtension(true, false),
        new KeyUsageExtension(true,
            KeyUsageExtension::DIGITAL_SIGNATURE |
             KeyUsageExtension::KEY_ENCIPHERMENT),
        // Permittet RFC822Name constraint 
        new NameConstraintsExtension(true,
            new GeneralSubtrees(
                new GeneralSubtree(
                    new RFC822Name('example.com')))));

$algo = SignatureAlgorithmIdentifierFactory::algoForAsymmetricCrypto(
    $ca_private_key->algorithmIdentifier(),
    new SHA256AlgorithmIdentifier());
$issuer_cert = $tbs_cert->sign($algo, $ca_private_key);

// Re-reading the certificate fails as described
$imported_issuer_cert = Certificate::fromPEM($issuer_cert->toPEM());
```

## Root cause analysis

The ```Integer overflow. in /vendor/sop/asn1/lib/ASN1/Util/BigInt.php:129``` occurs, because ```BigInt::fromSignedOctets()``` is called with the string value of the RFC822Name, in this example "example.com". That string is transcoded into an integer value as string representation and stored in a ```BigInt``` object.

When calling ```intVal()``` of the ```BigInt``` object, a RuntimeException is thrown, if the "integer-ized" string is bigger than ```PHP_INT_MAX``` (9223372036854775807 on x64 systems), which is valid. But after all, this does not make sense for the RFC822Name object.

### Root cause in ```GeneralSubtree::fromASN1()```

When reading the certificate also ```GeneralSubtree::fromASN1()``` is called. [This static function](https://github.com/sop/x509/blob/cd265f1075ed1be9580b37a78c840fee1340edcc/lib/X509/Certificate/Extension/NameConstraints/GeneralSubtree.php#L63) sets specific minimum and maximum fields, if a sequence has tagged elements with 0 or 1. **Notice**: RFC822Name objects are [tag 1](https://github.com/sop/x509/blob/cd265f1075ed1be9580b37a78c840fee1340edcc/lib/X509/GeneralName/GeneralName.php#L20) objects; other objects such as DNSName or IPAddress have tags greater than 1 ([see ```GeneralName``` class](https://github.com/sop/x509/blob/cd265f1075ed1be9580b37a78c840fee1340edcc/lib/X509/GeneralName/GeneralName.php#L18)).

It is currently unclear why minimum and maximum fields are processed in the conectext of Name Constraints, as RFC 5280 states:

> Within this profile, the minimum and maximum fields are not used with any name forms, thus, the minimum MUST be zero, and maximum MUST be absent.

If a RFC822Name Constraint is processed and the maximum field remains unset (i.e. [lines 72 to 75](https://github.com/sop/x509/blob/cd265f1075ed1be9580b37a78c840fee1340edcc/lib/X509/Certificate/Extension/NameConstraints/GeneralSubtree.php#L72) are omitted), the certificate can be read properly.

## Resolution
1. I suggest to analyze in which situation minimum and maximum fields need to be set for subtrees.
1. Furthermore, it needs to be discussed whether other subtree sequences have been wrongly processed while errors were not apparent.
1. Finally, name constraints should set the minium field to 0 and unset maximum field or reject the certificate, as RFC 5280 suggests.

**Comment by sop** [comment]
Thanks for a thorough report!
Indeed the problem was that `GeneralName` is a choice, thus having implicit tags, which would collide with _minimum_ and _maximum_ fields when _otherName_ or _rfc822Name_ options were used.

I've now fixed the issue and published a new version.

**Comment by 5pr1nz** [comment]
Wow, that's an awesome response time. Thanks a lot @sop !
